name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python 3.9"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
      - uses: "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065" # v5.6.0
        with:
          python-version: '3.9'
      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz graphviz-dev
      - name: Install dependencies
        run: |
          pip install pipenv
          pip install build
          pipenv install --dev --system
          pip install setuptools==70.3.0
      - name: Test
        run: |
          pipenv run pytest
      - name: Build
        run: |
          python -m build
